// Mocks generated by Mockito 5.4.6 from annotations
// in astr/test/features/dashboard/presentation/providers/weather_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:astr/core/error/failure.dart' as _i5;
import 'package:astr/features/context/domain/entities/geo_location.dart' as _i7;
import 'package:astr/features/dashboard/domain/entities/daily_weather_data.dart'
    as _i9;
import 'package:astr/features/dashboard/domain/entities/hourly_forecast.dart'
    as _i10;
import 'package:astr/features/dashboard/domain/entities/weather.dart' as _i6;
import 'package:astr/features/dashboard/domain/repositories/i_weather_repository.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IWeatherRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockIWeatherRepository extends _i1.Mock
    implements _i2.IWeatherRepository {
  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.Weather>> getWeather(
          _i7.GeoLocation? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getWeather,
          [location],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i6.Weather>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, _i6.Weather>>(
          this,
          Invocation.method(
            #getWeather,
            [location],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<_i4.Either<_i5.Failure, _i6.Weather>>.value(
                _i8.dummyValue<_i4.Either<_i5.Failure, _i6.Weather>>(
          this,
          Invocation.method(
            #getWeather,
            [location],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.Weather>>);

  @override
  _i3.Future<
      _i4.Either<_i5.Failure, List<_i9.DailyWeatherData>>> getDailyForecast(
          _i7.GeoLocation? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDailyForecast,
          [location],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<_i9.DailyWeatherData>>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, List<_i9.DailyWeatherData>>>(
          this,
          Invocation.method(
            #getDailyForecast,
            [location],
          ),
        )),
        returnValueForMissingStub: _i3
            .Future<_i4.Either<_i5.Failure, List<_i9.DailyWeatherData>>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, List<_i9.DailyWeatherData>>>(
          this,
          Invocation.method(
            #getDailyForecast,
            [location],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i9.DailyWeatherData>>>);

  @override
  _i3.Future<
      _i4.Either<_i5.Failure, List<_i10.HourlyForecast>>> getHourlyForecast(
          _i7.GeoLocation? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHourlyForecast,
          [location],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<_i10.HourlyForecast>>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, List<_i10.HourlyForecast>>>(
          this,
          Invocation.method(
            #getHourlyForecast,
            [location],
          ),
        )),
        returnValueForMissingStub: _i3
            .Future<_i4.Either<_i5.Failure, List<_i10.HourlyForecast>>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, List<_i10.HourlyForecast>>>(
          this,
          Invocation.method(
            #getHourlyForecast,
            [location],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i10.HourlyForecast>>>);
}
