// Mocks generated by Mockito 5.4.6 from annotations
// in astr/test/features/profile/data/repositories/location_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:astr/core/engine/models/result.dart' as _i5;
import 'package:astr/features/data_layer/services/h3_service.dart' as _i8;
import 'package:astr/features/profile/data/datasources/location_database_service.dart'
    as _i3;
import 'package:h3_flutter/h3_flutter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:sqflite_common/sqlite_api.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeH3_0 extends _i1.SmartFake implements _i2.H3 {
  _FakeH3_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [LocationDatabaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationDatabaseService extends _i1.Mock
    implements _i3.LocationDatabaseService {
  MockLocationDatabaseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized => (super.noSuchMethod(
        Invocation.getter(#isInitialized),
        returnValue: false,
      ) as bool);

  @override
  _i4.Future<_i5.Result<_i6.Database>> getDatabase() => (super.noSuchMethod(
        Invocation.method(
          #getDatabase,
          [],
        ),
        returnValue: _i4.Future<_i5.Result<_i6.Database>>.value(
            _i7.dummyValue<_i5.Result<_i6.Database>>(
          this,
          Invocation.method(
            #getDatabase,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Result<_i6.Database>>);

  @override
  _i4.Future<_i5.Result<void>> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue:
            _i4.Future<_i5.Result<void>>.value(_i7.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #initialize,
            [],
          ),
        )),
      ) as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<void>> insert(Map<String, dynamic>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #insert,
          [values],
        ),
        returnValue:
            _i4.Future<_i5.Result<void>>.value(_i7.dummyValue<_i5.Result<void>>(
          this,
          Invocation.method(
            #insert,
            [values],
          ),
        )),
      ) as _i4.Future<_i5.Result<void>>);

  @override
  _i4.Future<_i5.Result<int>> update(
    Map<String, dynamic>? values, {
    required String? where,
    required List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #update,
          [values],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue:
            _i4.Future<_i5.Result<int>>.value(_i7.dummyValue<_i5.Result<int>>(
          this,
          Invocation.method(
            #update,
            [values],
            {
              #where: where,
              #whereArgs: whereArgs,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<int>>);

  @override
  _i4.Future<_i5.Result<int>> delete({
    required String? where,
    required List<Object?>? whereArgs,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
          {
            #where: where,
            #whereArgs: whereArgs,
          },
        ),
        returnValue:
            _i4.Future<_i5.Result<int>>.value(_i7.dummyValue<_i5.Result<int>>(
          this,
          Invocation.method(
            #delete,
            [],
            {
              #where: where,
              #whereArgs: whereArgs,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<int>>);

  @override
  _i4.Future<_i5.Result<List<Map<String, dynamic>>>> query({
    List<String>? columns,
    String? where,
    List<Object?>? whereArgs,
    String? orderBy,
    int? limit,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #query,
          [],
          {
            #columns: columns,
            #where: where,
            #whereArgs: whereArgs,
            #orderBy: orderBy,
            #limit: limit,
          },
        ),
        returnValue: _i4.Future<_i5.Result<List<Map<String, dynamic>>>>.value(
            _i7.dummyValue<_i5.Result<List<Map<String, dynamic>>>>(
          this,
          Invocation.method(
            #query,
            [],
            {
              #columns: columns,
              #where: where,
              #whereArgs: whereArgs,
              #orderBy: orderBy,
              #limit: limit,
            },
          ),
        )),
      ) as _i4.Future<_i5.Result<List<Map<String, dynamic>>>>);

  @override
  _i4.Future<_i5.Result<List<Map<String, dynamic>>>> rawQuery(
    String? sql, [
    List<Object?>? arguments,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #rawQuery,
          [
            sql,
            arguments,
          ],
        ),
        returnValue: _i4.Future<_i5.Result<List<Map<String, dynamic>>>>.value(
            _i7.dummyValue<_i5.Result<List<Map<String, dynamic>>>>(
          this,
          Invocation.method(
            #rawQuery,
            [
              sql,
              arguments,
            ],
          ),
        )),
      ) as _i4.Future<_i5.Result<List<Map<String, dynamic>>>>);

  @override
  _i4.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [H3Service].
///
/// See the documentation for Mockito's code generation for more information.
class MockH3Service extends _i1.Mock implements _i8.H3Service {
  MockH3Service() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.H3 get h3 => (super.noSuchMethod(
        Invocation.getter(#h3),
        returnValue: _FakeH3_0(
          this,
          Invocation.getter(#h3),
        ),
      ) as _i2.H3);

  @override
  BigInt latLonToH3(
    double? lat,
    double? lon,
    int? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #latLonToH3,
          [
            lat,
            lon,
            resolution,
          ],
        ),
        returnValue: _i7.dummyValue<BigInt>(
          this,
          Invocation.method(
            #latLonToH3,
            [
              lat,
              lon,
              resolution,
            ],
          ),
        ),
      ) as BigInt);
}
