// Mocks generated by Mockito 5.4.6 from annotations
// in astr/test/features/dashboard/data/repositories/weather_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:astr/features/context/domain/entities/geo_location.dart' as _i4;
import 'package:astr/features/dashboard/data/datasources/open_meteo_weather_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OpenMeteoWeatherService].
///
/// See the documentation for Mockito's code generation for more information.
class MockOpenMeteoWeatherService extends _i1.Mock
    implements _i2.OpenMeteoWeatherService {
  MockOpenMeteoWeatherService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<double> getCloudCover(_i4.GeoLocation? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCloudCover,
          [location],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<Map<String, dynamic>> getHourlyForecast(
          _i4.GeoLocation? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getHourlyForecast,
          [location],
        ),
        returnValue:
            _i3.Future<Map<String, dynamic>>.value(<String, dynamic>{}),
      ) as _i3.Future<Map<String, dynamic>>);
}
