// Mocks generated by Mockito 5.4.6 from annotations
// in astr/test/features/profile/presentation/widgets/saved_locations_list_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:astr/core/error/failure.dart' as _i5;
import 'package:astr/core/services/i_location_service.dart' as _i8;
import 'package:astr/features/context/domain/entities/geo_location.dart' as _i9;
import 'package:astr/features/profile/data/repositories/profile_repository.dart'
    as _i2;
import 'package:astr/features/profile/domain/entities/saved_location.dart'
    as _i6;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> saveLocation(
          _i6.SavedLocation? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveLocation,
          [location],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #saveLocation,
            [location],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, List<_i6.SavedLocation>>>
      getSavedLocations() => (super.noSuchMethod(
            Invocation.method(
              #getSavedLocations,
              [],
            ),
            returnValue: _i3
                .Future<_i4.Either<_i5.Failure, List<_i6.SavedLocation>>>.value(
                _i7.dummyValue<
                    _i4.Either<_i5.Failure, List<_i6.SavedLocation>>>(
              this,
              Invocation.method(
                #getSavedLocations,
                [],
              ),
            )),
          ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.SavedLocation>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, void>> deleteLocation(String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocation,
          [id],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, void>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, void>>(
          this,
          Invocation.method(
            #deleteLocation,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, void>>);
}

/// A class which mocks [ILocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocationService extends _i1.Mock implements _i8.ILocationService {
  MockILocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i9.GeoLocation>> getCurrentLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i3.Future<_i4.Either<_i5.Failure, _i9.GeoLocation>>.value(
            _i7.dummyValue<_i4.Either<_i5.Failure, _i9.GeoLocation>>(
          this,
          Invocation.method(
            #getCurrentLocation,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i9.GeoLocation>>);
}
