// Mocks generated by Mockito 5.4.6 from annotations
// in astr/test/features/catalog/presentation/providers/object_detail_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:astr/core/error/failure.dart' as _i5;
import 'package:astr/features/catalog/domain/entities/celestial_object.dart'
    as _i6;
import 'package:astr/features/catalog/domain/entities/celestial_type.dart'
    as _i7;
import 'package:astr/features/catalog/domain/repositories/i_catalog_repository.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ICatalogRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockICatalogRepository extends _i1.Mock
    implements _i2.ICatalogRepository {
  MockICatalogRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<
      _i4.Either<_i5.Failure, List<_i6.CelestialObject>>> getObjectsByType(
          _i7.CelestialType? type) =>
      (super.noSuchMethod(
        Invocation.method(
          #getObjectsByType,
          [type],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<_i6.CelestialObject>>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, List<_i6.CelestialObject>>>(
          this,
          Invocation.method(
            #getObjectsByType,
            [type],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.CelestialObject>>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.CelestialObject>> getObjectById(
          String? id) =>
      (super.noSuchMethod(
        Invocation.method(
          #getObjectById,
          [id],
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.CelestialObject>>.value(
                _i8.dummyValue<_i4.Either<_i5.Failure, _i6.CelestialObject>>(
          this,
          Invocation.method(
            #getObjectById,
            [id],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.CelestialObject>>);

  @override
  _i3.Future<
      _i4.Either<_i5.Failure,
          List<_i6.CelestialObject>>> getAllObjects() => (super.noSuchMethod(
        Invocation.method(
          #getAllObjects,
          [],
        ),
        returnValue: _i3
            .Future<_i4.Either<_i5.Failure, List<_i6.CelestialObject>>>.value(
            _i8.dummyValue<_i4.Either<_i5.Failure, List<_i6.CelestialObject>>>(
          this,
          Invocation.method(
            #getAllObjects,
            [],
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, List<_i6.CelestialObject>>>);
}
