// Mocks generated by Mockito 5.4.6 from annotations
// in astr/test/core/services/light_pollution/light_pollution_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:astr/core/engine/models/location.dart' as _i4;
import 'package:astr/core/services/light_pollution/data/offline_lp_data_source.dart'
    as _i5;
import 'package:astr/core/services/light_pollution/data/online_lp_data_source.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OnlineLPDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOnlineLPDataSource extends _i1.Mock
    implements _i2.OnlineLPDataSource {
  MockOnlineLPDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int?> getBortleClass(_i4.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBortleClass,
          [location],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [OfflineLPDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockOfflineLPDataSource extends _i1.Mock
    implements _i5.OfflineLPDataSource {
  MockOfflineLPDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<int?> getBortleClass(_i4.Location? location) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBortleClass,
          [location],
        ),
        returnValue: _i3.Future<int?>.value(),
      ) as _i3.Future<int?>);

  @override
  void clearCache() => super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
