// Mocks generated by Mockito 5.4.6 from annotations
// in astr/test/features/splash/domain/services/smart_launch_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:astr/core/error/failure.dart' as _i7;
import 'package:astr/core/services/i_location_service.dart' as _i4;
import 'package:astr/features/context/domain/entities/geo_location.dart' as _i8;
import 'package:astr/features/data_layer/models/zone_data.dart' as _i3;
import 'package:astr/features/data_layer/repositories/cached_zone_repository.dart'
    as _i11;
import 'package:astr/features/data_layer/services/h3_service.dart' as _i10;
import 'package:fpdart/fpdart.dart' as _i6;
import 'package:h3_flutter/h3_flutter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeH3_0 extends _i1.SmartFake implements _i2.H3 {
  _FakeH3_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeZoneData_1 extends _i1.SmartFake implements _i3.ZoneData {
  _FakeZoneData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ILocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockILocationService extends _i1.Mock implements _i4.ILocationService {
  MockILocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i6.Either<_i7.Failure, _i8.GeoLocation>> getCurrentLocation() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentLocation,
          [],
        ),
        returnValue: _i5.Future<_i6.Either<_i7.Failure, _i8.GeoLocation>>.value(
            _i9.dummyValue<_i6.Either<_i7.Failure, _i8.GeoLocation>>(
          this,
          Invocation.method(
            #getCurrentLocation,
            [],
          ),
        )),
      ) as _i5.Future<_i6.Either<_i7.Failure, _i8.GeoLocation>>);
}

/// A class which mocks [H3Service].
///
/// See the documentation for Mockito's code generation for more information.
class MockH3Service extends _i1.Mock implements _i10.H3Service {
  MockH3Service() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.H3 get h3 => (super.noSuchMethod(
        Invocation.getter(#h3),
        returnValue: _FakeH3_0(
          this,
          Invocation.getter(#h3),
        ),
      ) as _i2.H3);

  @override
  BigInt latLonToH3(
    double? lat,
    double? lon,
    int? resolution,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #latLonToH3,
          [
            lat,
            lon,
            resolution,
          ],
        ),
        returnValue: _i9.dummyValue<BigInt>(
          this,
          Invocation.method(
            #latLonToH3,
            [
              lat,
              lon,
              resolution,
            ],
          ),
        ),
      ) as BigInt);
}

/// A class which mocks [CachedZoneRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCachedZoneRepository extends _i1.Mock
    implements _i11.CachedZoneRepository {
  MockCachedZoneRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i3.ZoneData> getZoneData(BigInt? h3Index) => (super.noSuchMethod(
        Invocation.method(
          #getZoneData,
          [h3Index],
        ),
        returnValue: _i5.Future<_i3.ZoneData>.value(_FakeZoneData_1(
          this,
          Invocation.method(
            #getZoneData,
            [h3Index],
          ),
        )),
      ) as _i5.Future<_i3.ZoneData>);

  @override
  _i3.ZoneData getZoneDataSync(BigInt? h3Index) => (super.noSuchMethod(
        Invocation.method(
          #getZoneDataSync,
          [h3Index],
        ),
        returnValue: _FakeZoneData_1(
          this,
          Invocation.method(
            #getZoneDataSync,
            [h3Index],
          ),
        ),
      ) as _i3.ZoneData);

  @override
  _i5.Future<void> prefetchZones(List<BigInt>? h3Indices) =>
      (super.noSuchMethod(
        Invocation.method(
          #prefetchZones,
          [h3Indices],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  Map<String, dynamic> getCacheStats() => (super.noSuchMethod(
        Invocation.method(
          #getCacheStats,
          [],
        ),
        returnValue: <String, dynamic>{},
      ) as Map<String, dynamic>);

  @override
  _i5.Future<void> clearCache() => (super.noSuchMethod(
        Invocation.method(
          #clearCache,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}
