// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:astr/features/dashboard/data/models/weather_cache_entry.dart';
import 'package:astr/features/data_layer/models/zone_cache_entry.dart';
import 'package:astr/features/profile/domain/entities/saved_location.dart';
import 'package:astr/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SavedLocationAdapter());
    registerAdapter(ThemeUiModelAdapter());
    registerAdapter(WeatherCacheEntryAdapter());
    registerAdapter(ZoneCacheEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SavedLocationAdapter());
    registerAdapter(ThemeUiModelAdapter());
    registerAdapter(WeatherCacheEntryAdapter());
    registerAdapter(ZoneCacheEntryAdapter());
  }
}
