// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:astr/features/profile/domain/entities/saved_location.dart';
import 'package:astr/hive/hive_adapters.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(SavedLocationAdapter());
    registerAdapter(ThemeUiModelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(SavedLocationAdapter());
    registerAdapter(ThemeUiModelAdapter());
  }
}
