// Mocks generated by Mockito 5.4.6 from annotations
// in astr/test/features/catalog/domain/services/visibility_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:astr/features/astronomy/domain/services/astronomy_service.dart'
    as _i2;
import 'package:astr/features/catalog/domain/entities/graph_point.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sweph/sweph.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AstronomyService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAstronomyService extends _i1.Mock implements _i2.AstronomyService {
  MockAstronomyService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<Map<String, DateTime?>> calculateRiseSetTransit({
    required _i4.HeavenlyBody? body,
    String? starName,
    required DateTime? date,
    required double? lat,
    required double? long,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateRiseSetTransit,
          [],
          {
            #body: body,
            #starName: starName,
            #date: date,
            #lat: lat,
            #long: long,
          },
        ),
        returnValue:
            _i3.Future<Map<String, DateTime?>>.value(<String, DateTime?>{}),
      ) as _i3.Future<Map<String, DateTime?>>);

  @override
  _i3.Future<List<_i5.GraphPoint>> calculateAltitudeTrajectory({
    required _i4.HeavenlyBody? body,
    required DateTime? startTime,
    required double? lat,
    required double? long,
    Duration? duration = const Duration(hours: 12),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateAltitudeTrajectory,
          [],
          {
            #body: body,
            #startTime: startTime,
            #lat: lat,
            #long: long,
            #duration: duration,
          },
        ),
        returnValue: _i3.Future<List<_i5.GraphPoint>>.value(<_i5.GraphPoint>[]),
      ) as _i3.Future<List<_i5.GraphPoint>>);

  @override
  _i3.Future<List<_i5.GraphPoint>> calculateFixedObjectTrajectory({
    required double? ra,
    required double? dec,
    required DateTime? startTime,
    required double? lat,
    required double? long,
    Duration? duration = const Duration(hours: 12),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateFixedObjectTrajectory,
          [],
          {
            #ra: ra,
            #dec: dec,
            #startTime: startTime,
            #lat: lat,
            #long: long,
            #duration: duration,
          },
        ),
        returnValue: _i3.Future<List<_i5.GraphPoint>>.value(<_i5.GraphPoint>[]),
      ) as _i3.Future<List<_i5.GraphPoint>>);

  @override
  _i3.Future<List<_i5.GraphPoint>> calculateMoonTrajectory({
    required DateTime? startTime,
    required double? lat,
    required double? long,
    Duration? duration = const Duration(hours: 12),
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #calculateMoonTrajectory,
          [],
          {
            #startTime: startTime,
            #lat: lat,
            #long: long,
            #duration: duration,
          },
        ),
        returnValue: _i3.Future<List<_i5.GraphPoint>>.value(<_i5.GraphPoint>[]),
      ) as _i3.Future<List<_i5.GraphPoint>>);

  @override
  _i3.Future<double> getMoonPhase(DateTime? time) => (super.noSuchMethod(
        Invocation.method(
          #getMoonPhase,
          [time],
        ),
        returnValue: _i3.Future<double>.value(0.0),
      ) as _i3.Future<double>);

  @override
  _i3.Future<Map<String, DateTime>> getNightWindow({
    required DateTime? date,
    required double? lat,
    required double? long,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNightWindow,
          [],
          {
            #date: date,
            #lat: lat,
            #long: long,
          },
        ),
        returnValue:
            _i3.Future<Map<String, DateTime>>.value(<String, DateTime>{}),
      ) as _i3.Future<Map<String, DateTime>>);

  @override
  _i3.Future<void> checkInitialized() => (super.noSuchMethod(
        Invocation.method(
          #checkInitialized,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
