// Mocks generated by Mockito 5.4.6 from annotations
// in astr/test/features/catalog/domain/services/visibility_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:astr/core/error/failure.dart' as _i5;
import 'package:astr/features/astronomy/domain/entities/celestial_body.dart'
    as _i7;
import 'package:astr/features/astronomy/domain/entities/celestial_position.dart'
    as _i6;
import 'package:astr/features/astronomy/domain/entities/moon_phase_info.dart'
    as _i9;
import 'package:astr/features/astronomy/domain/repositories/i_astro_engine.dart'
    as _i2;
import 'package:fpdart/fpdart.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [IAstroEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockIAstroEngine extends _i1.Mock implements _i2.IAstroEngine {
  MockIAstroEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i6.CelestialPosition>> getPosition({
    required _i7.CelestialBody? body,
    required DateTime? time,
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPosition,
          [],
          {
            #body: body,
            #time: time,
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.CelestialPosition>>.value(
                _i8.dummyValue<_i4.Either<_i5.Failure, _i6.CelestialPosition>>(
          this,
          Invocation.method(
            #getPosition,
            [],
            {
              #body: body,
              #time: time,
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.CelestialPosition>>);

  @override
  _i3.Future<
      _i4.Either<_i5.Failure, _i6.CelestialPosition>> getDeepSkyPosition({
    required double? ra,
    required double? dec,
    required String? name,
    required DateTime? time,
    required double? latitude,
    required double? longitude,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDeepSkyPosition,
          [],
          {
            #ra: ra,
            #dec: dec,
            #name: name,
            #time: time,
            #latitude: latitude,
            #longitude: longitude,
          },
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i6.CelestialPosition>>.value(
                _i8.dummyValue<_i4.Either<_i5.Failure, _i6.CelestialPosition>>(
          this,
          Invocation.method(
            #getDeepSkyPosition,
            [],
            {
              #ra: ra,
              #dec: dec,
              #name: name,
              #time: time,
              #latitude: latitude,
              #longitude: longitude,
            },
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i6.CelestialPosition>>);

  @override
  _i3.Future<_i4.Either<_i5.Failure, _i9.MoonPhaseInfo>> getMoonPhaseInfo(
          {required DateTime? time}) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMoonPhaseInfo,
          [],
          {#time: time},
        ),
        returnValue:
            _i3.Future<_i4.Either<_i5.Failure, _i9.MoonPhaseInfo>>.value(
                _i8.dummyValue<_i4.Either<_i5.Failure, _i9.MoonPhaseInfo>>(
          this,
          Invocation.method(
            #getMoonPhaseInfo,
            [],
            {#time: time},
          ),
        )),
      ) as _i3.Future<_i4.Either<_i5.Failure, _i9.MoonPhaseInfo>>);
}
